RECOMMENDATIONS = {
    "Docker": "Learn Docker Basics and Containerization.",
    "TensorFlow": "Complete TensorFlow Fundamentals and build one Deep Learning project.",
    "Machine Learning": "Study Supervised and Unsupervised Machine Learning algorithms.",
    "Python": "Practice Python OOP, File Handling and Projects.",
    "SQL": "Practice Joins, Group By, Window Functions and SQL Queries.",
    "React": "Build React Projects using Components, Hooks and Routing.",
    "MongoDB": "Learn CRUD Operations and Aggregation Framework.",
    "Git": "Practice Git Commands and GitHub Workflow.",
    "Java": "Strengthen OOP and Java Collections.",
    "C++": "Practice STL, OOP, and competitive programming problems.",
    "GitHub": "Learn repository management and pull requests.",
    "HTML": "Build responsive web pages.",
    "CSS": "Learn Flexbox and CSS Grid.",
    "JavaScript": "Practice ES6+, DOM, and Async JavaScript.",
    "Node.js": "Learn REST APIs using Express.",
    "Express.js": "Practice backend API development.",
    "AWS": "Learn EC2, S3, and IAM basics.",
    "Object-Oriented Programming": "Master Classes, Objects, Inheritance, Polymorphism, Abstraction, and Encapsulation through coding exercises.",
  "Data Structures & Algorithms": "Practice Arrays, Linked Lists, Trees, Graphs, Dynamic Programming, and solve problems on LeetCode.",
  "DBMS": "Study Normalization, Indexing, Transactions, ACID Properties, and SQL optimization.",
  "Operating Systems": "Learn Processes, Threads, Scheduling, Deadlocks, Memory Management, and Virtual Memory.",
  "Computer Networks": "Understand TCP/IP, HTTP/HTTPS, DNS, OSI Model, Routing, and Network Security.",
  "Problem Solving": "Solve coding challenges daily on LeetCode, HackerRank, or Codeforces.",
  "System Design": "Learn HLD/LLD concepts, Load Balancing, Caching, Databases, and Distributed Systems.",
  "Distributed Systems": "Study Scalability, Replication, Sharding, CAP Theorem, and Event-Driven Architecture.",
  "Spring Boot": "Build REST APIs with Spring Boot, Spring Data JPA, and Spring Security.",
  "Django": "Develop web applications using Django ORM, Authentication, and REST Framework.",
  "Flask": "Build lightweight REST APIs and backend applications using Flask.",
  "FastAPI": "Create high-performance REST APIs with FastAPI, Pydantic, and Async programming.",
  "REST APIs": "Design CRUD APIs, understand HTTP methods, status codes, authentication, and testing.",
  "NumPy": "Practice array operations, broadcasting, linear algebra, and numerical computing.",
  "Pandas": "Perform data cleaning, preprocessing, aggregation, merging, and visualization.",
  "Scikit-learn": "Build ML models using preprocessing, feature engineering, training, and evaluation.",
  "PyTorch": "Implement Deep Learning models using tensors, autograd, CNNs, and transfer learning.",
  "Deep Learning": "Study Neural Networks, CNNs, RNNs, Transformers, and optimization techniques.",
  "Statistics": "Learn Probability, Distributions, Hypothesis Testing, Regression, and Statistical Analysis.",
  "Data Visualization": "Create charts using Matplotlib, Seaborn, Power BI, and Tableau.",
  "Feature Engineering": "Practice feature selection, encoding, scaling, and transformation techniques.",
  "NLP": "Learn Text Processing, Tokenization, Embeddings, Transformers, and LLM basics.",
  "Computer Vision": "Build image classification and object detection projects using OpenCV and Deep Learning.",
  "MLOps": "Learn ML deployment, model monitoring, CI/CD, Docker, and MLflow pipelines.",
  "MLflow": "Track ML experiments, model versioning, and deployment using MLflow.",
  "Kubernetes": "Learn Pods, Deployments, Services, ConfigMaps, and Kubernetes scaling.",
  "Redis": "Implement caching, sessions, pub/sub messaging, and rate limiting.",
  "Kafka": "Build event-driven applications using Kafka producers, consumers, and topics.",
  "RabbitMQ": "Practice asynchronous messaging using exchanges, queues, and routing keys.",
  "Celery": "Implement background task processing with Celery and Redis.",
  "Authentication (JWT/OAuth)": "Implement secure authentication using JWT, OAuth2, refresh tokens, and role-based authorization.",
  "Microservices": "Build independent services communicating through REST APIs or messaging systems.",
  "TypeScript": "Learn static typing, interfaces, generics, and TypeScript with React.",
  "Angular": "Build SPA applications using Components, Services, Routing, and RxJS.",
  "Next.js": "Create server-side rendered React applications with routing and API routes.",
  "Redux": "Manage global state using Redux Toolkit and asynchronous actions.",
  "Responsive Design": "Build mobile-first layouts using Flexbox, Grid, and Media Queries.",
  "Browser Debugging": "Debug applications using Chrome DevTools, breakpoints, and network analysis.",
  "UI Development": "Develop reusable, accessible, and responsive user interfaces.",
  "WebSockets": "Build real-time applications using WebSockets and Socket.IO.",
  "Performance Optimization": "Improve application performance using lazy loading, memoization, caching, and code splitting.",
  "CI/CD": "Automate build, testing, and deployment using GitHub Actions, Jenkins, or Azure DevOps.",
  "Agile Methodology": "Understand Scrum, Sprint Planning, Stand-ups, Retrospectives, and Jira workflow.",
  "Linux": "Practice Linux commands, shell scripting, permissions, processes, and networking.",
  "Shell Scripting": "Automate tasks using Bash scripting and Linux utilities.",
  "Go": "Learn Go syntax, concurrency using Goroutines, channels, and REST API development.",
  "C#": "Master OOP, LINQ, .NET Core, and ASP.NET Web API.",
  ".NET Core": "Develop REST APIs, dependency injection, Entity Framework Core, and authentication.",
  "Swift": "Build iOS applications using Swift, UIKit, and SwiftUI.",
  "Objective-C": "Understand Objective-C fundamentals and interoperability with Swift.",
  "SwiftUI": "Develop modern iOS user interfaces using SwiftUI.",
  "UIKit": "Build iOS applications using UIKit components and navigation.",
  "Xcode": "Learn project management, debugging, profiling, and iOS deployment using Xcode.",
  "Core ML": "Integrate Machine Learning models into iOS applications using Core ML.",
  "GraphQL": "Build APIs and consume GraphQL endpoints using queries, mutations, and subscriptions.",
  "Oracle Database": "Learn Oracle SQL, PL/SQL, indexing, stored procedures, and performance tuning.",
  "Oracle SQL": "Practice advanced SQL queries, joins, views, procedures, and triggers.",
  "Power BI": "Create interactive dashboards, DAX measures, and data models.",
  "Tableau": "Build business dashboards, visualizations, filters, and calculated fields.",
  "Excel": "Master Pivot Tables, Lookup Functions, Charts, Power Query, and Data Analysis.",
  "ETL": "Build ETL pipelines for extracting, transforming, and loading enterprise data.",
  "Snowflake": "Learn Snowflake architecture, warehouses, stages, and SQL optimization.",
  "BigQuery": "Practice cloud SQL analytics using Google BigQuery.",
  "Looker": "Create dashboards and reports using LookML and Looker Studio.",
  "Business Intelligence": "Learn KPI reporting, dashboards, and business analytics techniques.",
  "A/B Testing": "Understand hypothesis testing, experiment design, and statistical significance.",
  "Data Warehousing": "Study Star Schema, Snowflake Schema, ETL, and OLAP concepts."
}


def get_recommendations(missing_skills):
    suggestions = []

    for skill in missing_skills:
        if skill in RECOMMENDATIONS:
            suggestions.append((skill, RECOMMENDATIONS[skill]))

    return suggestions