# List of common technical skills

SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Node.js",
    "Express.js",
    "MongoDB",
    "MySQL",
    "SQL",
    "Git",
    "GitHub",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "TensorFlow",
    "PyTorch",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Streamlit",
    "Flask",
    "Django",
    "Bootstrap",
    "EJS",
    "Mongoose",
    "C#",
"Go",
"Swift",
"Objective-C",
"TypeScript",
"Next.js",
"Redux",
"Angular",
"Oracle SQL",
"Oracle Database",
"Computer Vision",
"MLflow",
"MLOps",
"FastAPI",
"REST APIs",
"GraphQL",
"Docker",
"Kubernetes",
"Redis",
"Kafka",
"RabbitMQ",
"Celery",
"AWS",
"Azure",
"Google Cloud Platform (GCP)",
"Oracle Cloud Infrastructure (OCI)",
"Data Structures & Algorithms",
"Object-Oriented Programming",
"DBMS",
"Operating Systems",
"Computer Networks",
"Problem Solving",
"System Design",
"Distributed Systems",
"Microservices",
"Authentication (JWT/OAuth)",
"Linux",
"Shell Scripting",
"CI/CD",
"Agile Methodology",
"Statistics",
"Feature Engineering",
"Data Visualization",
"Power BI",
"Tableau",
"Excel",
"ETL",
"Data Warehousing",
"Business Intelligence",
"A/B Testing",
"Snowflake",
"BigQuery",
"Looker"
]


def extract_skills(text):
    found_skills = []

    text = text.lower()

    for skill in SKILLS:
        if skill.lower() in text:
            found_skills.append(skill)

    return sorted(set(found_skills))